#!/usr/bin/env python3
"""
Phase 2 — generate local .woff2 font subsets for PortDesk.

Downloads Tajawal (Arabic + Latin) and JetBrains Mono (Latin) TTFs from the
Google Fonts GitHub mirror, subsets each to the unicode ranges PortDesk
actually uses, and writes the .woff2 outputs to extras/fonts/.

This is a ONE-TIME operation. The resulting .woff2 files are committed to
the repo so the server no longer needs to download/subset at runtime.

If the network is unavailable, the script exits 0 but prints a warning so
the calling make step does not fail — the SERVER.py code path that served
fonts via _ensure_fonts_subsets() has been removed, so missing .woff2 files
will simply 404 at the new /static/fonts/{file} endpoint. The operator can
re-run this script when network is available.
"""
from __future__ import annotations
import os
import sys
import shutil
import subprocess
import tempfile
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(HERE)
# Default destination: <repo>/extras/fonts/. Override with --dest for one-off
# runs (e.g. when generating into a sub-workspace).
FONTS_DIR = os.environ.get('PORTDESK_FONTS_DIR') or os.path.join(PROJECT_ROOT, 'extras', 'fonts')

# Font sources — SIL OFL licensed, redistribution permitted with attribution.
# Tajawal is fetched from the google/fonts mirror. JetBrains Mono is fetched
# from the upstream JetBrains/JetBrainsMono repo (the google/fonts copy is
# occasionally 403-blocked on jsdelivr due to file size).
FONT_SOURCES = {
    'tajawal-regular.ttf':    'https://cdn.jsdelivr.net/gh/google/fonts@main/ofl/tajawal/Tajawal-Regular.ttf',
    'tajawal-bold.ttf':       'https://cdn.jsdelivr.net/gh/google/fonts@main/ofl/tajawal/Tajawal-Bold.ttf',
    'tajawal-extrabold.ttf':  'https://cdn.jsdelivr.net/gh/google/fonts@main/ofl/tajawal/Tajawal-ExtraBold.ttf',
    'jetbrains-mono-regular.ttf': 'https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono@master/fonts/ttf/JetBrainsMono-Regular.ttf',
    'jetbrains-mono-bold.ttf':    'https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono@master/fonts/ttf/JetBrainsMono-Bold.ttf',
}

# Subset definitions: (input_ttf, output_woff2, unicode_ranges)
SUBSETS = [
    ('tajawal-regular.ttf',       'tajawal-regular-subset.woff2',
     'U+0600-06FF,U+0000-007F,U+00A0-00FF'),
    ('tajawal-bold.ttf',          'tajawal-bold-subset.woff2',
     'U+0600-06FF,U+0000-007F,U+00A0-00FF'),
    ('tajawal-extrabold.ttf',     'tajawal-extrabold-subset.woff2',
     'U+0600-06FF,U+0000-007F,U+00A0-00FF'),
    ('jetbrains-mono-regular.ttf','jetbrains-mono-subset.woff2',
     'U+0000-007F,U+00A0-00FF'),
    ('jetbrains-mono-bold.ttf',   'jetbrains-mono-bold-subset.woff2',
     'U+0000-007F,U+00A0-00FF'),
]

# CSS @font-face file. Served at /static/fonts/fonts.css by the new static route.
# Note: CLIENT.html loads this via <link rel="stylesheet" href="/static/fonts/fonts.css">.
FONTS_CSS = """\
/* PortDesk font subsets — generated by scripts/generate_font_subsets.py.
   Tajawal: OFL 1.1, https://fonts.google.com/specimen/Tajawal
   JetBrains Mono: OFL 1.1, https://fonts.google.com/specimen/JetBrains+Mono
   Redistribution permitted under the SIL Open Font License. */

@font-face {
  font-family: 'Tajawal';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('/static/fonts/tajawal-regular-subset.woff2') format('woff2');
}
@font-face {
  font-family: 'Tajawal';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url('/static/fonts/tajawal-bold-subset.woff2') format('woff2');
}
@font-face {
  font-family: 'Tajawal';
  font-style: normal;
  font-weight: 800;
  font-display: swap;
  src: url('/static/fonts/tajawal-extrabold-subset.woff2') format('woff2');
}
@font-face {
  font-family: 'JetBrains Mono';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('/static/fonts/jetbrains-mono-subset.woff2') format('woff2');
}
@font-face {
  font-family: 'JetBrains Mono';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url('/static/fonts/jetbrains-mono-bold-subset.woff2') format('woff2');
}
"""

def _fail(msg: str) -> None:
    print(f"  ⚠ {msg}", flush=True)

def _download(url: str, dest: str) -> bool:
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'portdesk-font-subset/1.0'})
        with urllib.request.urlopen(req, timeout=30) as resp:
            with open(dest, 'wb') as f:
                shutil.copyfileobj(resp, f)
        return True
    except Exception as e:
        _fail(f"download failed: {url} → {e}")
        return False

def _subset(inp: str, out: str, ranges: str) -> bool:
    try:
        # IMPORTANT: use --opt=value form (not --opt value). pyftsubset's
        # argparse treats trailing positional glyph names loosely, and the
        # space-separated form has been observed to swallow following flags
        # as "missing glyph names" in fontTools ≥4.50 (raises
        # MissingGlyphsSubsettingError listing the flag strings themselves).
        subprocess.run([
            'pyftsubset', inp,
            f'--unicodes={ranges}',
            '--flavor=woff2',
            f'--output-file={out}',
            '--layout-features=*',
            '--desubroutinize',
        ], check=True, capture_output=True, timeout=60)
        return True
    except subprocess.CalledProcessError as e:
        _fail(f"pyftsubset failed for {os.path.basename(out)}: "
              f"{e.stderr.decode(errors='replace') if e.stderr else e}")
        return False
    except Exception as e:
        _fail(f"pyftsubset error for {os.path.basename(out)}: {e}")
        return False

def main() -> int:
    os.makedirs(FONTS_DIR, exist_ok=True)

    # Skip if all outputs already exist
    expected = [os.path.join(FONTS_DIR, out) for _, out, _ in SUBSETS]
    expected.append(os.path.join(FONTS_DIR, 'fonts.css'))
    if all(os.path.exists(p) and os.path.getsize(p) > 0 for p in expected):
        print("  ✅ Font subsets already present in extras/fonts/", flush=True)
        return 0

    if not shutil.which('pyftsubset'):
        _fail("pyftsubset not on PATH — install fonttools (pip install fonttools)")
        return 1

    print("  📥 Downloading TTFs from Google Fonts mirror...", flush=True)
    with tempfile.TemporaryDirectory() as tmpdir:
        # Download all source TTFs
        downloaded = {}
        for local_name, url in FONT_SOURCES.items():
            local_path = os.path.join(tmpdir, local_name)
            if _download(url, local_path):
                downloaded[local_name] = local_path
                print(f"     ✓ {local_name}", flush=True)
            else:
                # Cannot proceed without all source TTFs
                return 1

        print("  ✂️  Generating .woff2 subsets via pyftsubset...", flush=True)
        for inp_name, out_name, ranges in SUBSETS:
            inp_path = downloaded.get(inp_name)
            if not inp_path:
                _fail(f"missing input {inp_name} — skipping {out_name}")
                continue
            out_path = os.path.join(FONTS_DIR, out_name)
            if _subset(inp_path, out_path, ranges):
                size_kb = os.path.getsize(out_path) / 1024
                print(f"     ✓ {out_name}  ({size_kb:.1f} KB)", flush=True)
            else:
                return 1

    # Write the CSS
    css_path = os.path.join(FONTS_DIR, 'fonts.css')
    with open(css_path, 'w', encoding='utf-8') as f:
        f.write(FONTS_CSS)
    print(f"     ✓ fonts.css", flush=True)

    print("  ✅ Font subsets ready in extras/fonts/", flush=True)
    return 0

if __name__ == '__main__':
    sys.exit(main())
